- name: Find baks
  hosts: 10.10.3.101
  tasks: 
    - name: Find all backup files
      ansible.builtin.find:
        paths: //10.10.3.101/volume1/ActiveBackupforBusiness/databases/postgres-parus8/ActiveBackup_2026-04-03_030015/home/usr/backups
        patterns: "*.gz"  
      register: found_backups
    - name: Select the latest backup
      ansible.builtin.set_fact:
        latest_backup: "{{ (found_backups.files | sort(attribute='mtime') | last).path }}"
